In [1]:
import os
os.listdir()

['.ipynb_checkpoints',
 'P.ipynb',
 'smallgray.png',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx']

In [2]:
import pandas
df5=pandas.read_csv("supermarkets-semi-colons.txt",sep=";")
df5.set_index("ID")

Address           City             State Country          Name  \
ID                                                                           
1      3666 21st St  San Francisco          CA 94114     USA       Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA   Super River   
4      3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA       Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [3]:
 list(df5.loc[:,"Country"])

['USA', 'USA', 'USA', 'USA', 'USA', 'USA']

In [4]:
df5

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [5]:
df5.iloc[0,1:4]

Address     3666 21st St
City       San Francisco
State           CA 94114
Name: 0, dtype: object

In [6]:
df6=df5
df5["Continent"]=df5.shape[0]*["North America"]

In [7]:
df5["Continent"]=df5["Country"] + "," + "North America"

In [8]:
df5

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees          Continent  
0          8  USA,North America  
1         15  USA,North America  
2         25  USA,North America  
3         10  USA,North America  
4         12  USA,North America  
5         20  USA,North America

In [9]:
df5_t=df5.T

In [10]:
df5_t

0                  1                  2  \
ID                         1                  2                  3   
Address         3666 21st St     735 Dolores St        332 Hill St   
City           San Francisco      San Francisco      San Francisco   
State               CA 94114           CA 94119   California 94114   
Country                  USA                USA                USA   
Name                 Madeira        Bready Shop        Super River   
Employees                  8                 15                 25   
Continent  USA,North America  USA,North America  USA,North America   

                           3                  4                  5  
ID                         4                  5                  6  
Address         3995 23rd St    1056 Sanchez St    551 Alvarado St  
City           San Francisco      San Francisco      San Francisco  
State               CA 94114         California           CA 94114  
Country                  USA                USA                USA  
Name              Ben's Shop            Sanchez         Richvalley  
Employees                 10                 12                 20  
Continent  USA,North America  USA,North America  USA,North America

In [11]:
#Geocoding
dm=pandas.merge(left=df5,right=df6,on="ID")

In [12]:
dm

ID        Address_x         City_x           State_x Country_x  \
0   1     3666 21st St  San Francisco          CA 94114       USA   
1   2   735 Dolores St  San Francisco          CA 94119       USA   
2   3      332 Hill St  San Francisco  California 94114       USA   
3   4     3995 23rd St  San Francisco          CA 94114       USA   
4   5  1056 Sanchez St  San Francisco        California       USA   
5   6  551 Alvarado St  San Francisco          CA 94114       USA   

         Name_x  Employees_x        Continent_x        Address_y  \
0       Madeira            8  USA,North America     3666 21st St   
1   Bready Shop           15  USA,North America   735 Dolores St   
2   Super River           25  USA,North America      332 Hill St   
3    Ben's Shop           10  USA,North America     3995 23rd St   
4       Sanchez           12  USA,North America  1056 Sanchez St   
5    Richvalley           20  USA,North America  551 Alvarado St   

          City_y           State_y Country_y        Name_y  Employees_y  \
0  San Francisco          CA 94114       USA       Madeira            8   
1  San Francisco          CA 94119       USA   Bready Shop           15   
2  San Francisco  California 94114       USA   Super River           25   
3  San Francisco          CA 94114       USA    Ben's Shop           10   
4  San Francisco        California       USA       Sanchez           12   
5  San Francisco          CA 94114       USA    Richvalley           20   

         Continent_y  
0  USA,North America  
1  USA,North America  
2  USA,North America  
3  USA,North America  
4  USA,North America  
5  USA,North America

In [13]:
#import geopy
#dir(geopy)
from geopy.geocoders import Nominatim

In [14]:
#total = 0
#[1,2,3,4,5].each {|x| total += x*x }
#[5,4,3,2].each {|x| total -= x*x }

In [15]:
nom=Nominatim()

In [16]:
n=nom.geocode("3995 23rd St, San Francisco, CA 94114")

In [17]:
df5

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees          Continent  
0          8  USA,North America  
1         15  USA,North America  
2         25  USA,North America  
3         10  USA,North America  
4         12  USA,North America  
5         20  USA,North America

In [18]:
df5["Address"]=df5["Address"]+", "+df5["City"]+", "+df5["State"]+", "+df5["Country"]
df5

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country          Name  Employees          Continent  
0          CA 94114     USA       Madeira          8  USA,North America  
1          CA 94119     USA   Bready Shop         15  USA,North America  
2  California 94114     USA   Super River         25  USA,North America  
3          CA 94114     USA    Ben's Shop         10  USA,North America  
4        California     USA       Sanchez         12  USA,North America  
5          CA 94114     USA    Richvalley         20  USA,North America

In [19]:
df5["Coordinates"]=df5["Address"].apply(nom.geocode)
df5

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country          Name  Employees          Continent  \
0          CA 94114     USA       Madeira          8  USA,North America   
1          CA 94119     USA   Bready Shop         15  USA,North America   
2  California 94114     USA   Super River         25  USA,North America   
3          CA 94114     USA    Ben's Shop         10  USA,North America   
4        California     USA       Sanchez         12  USA,North America   
5          CA 94114     USA    Richvalley         20  USA,North America   

                                         Coordinates  
0  (3666, 21st Street, Noe Valley, SF, California...  
1                                               None  
2  (332, Hill Street, Liberty Street Historic Dis...  
3  (3995, 23rd Street, Noe Valley, SF, California...  
4  (1056, Sanchez Street, Noe Valley, SF, Califor...  
5  (551, Alvarado Street, Noe Valley, SF, Califor...

In [20]:
#df5.Coordinates
df5.Coordinates[0].longitude

-122.429343346939

In [21]:
df5["latitude"]=df5["Coordinates"].apply(lambda x: x.latitude if x!= None else None)
df5["longitude"]=df5["Coordinates"].apply(lambda x: x.longitude if x!= None else None)

In [22]:
df5

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country          Name  Employees          Continent  \
0          CA 94114     USA       Madeira          8  USA,North America   
1          CA 94119     USA   Bready Shop         15  USA,North America   
2  California 94114     USA   Super River         25  USA,North America   
3          CA 94114     USA    Ben's Shop         10  USA,North America   
4        California     USA       Sanchez         12  USA,North America   
5          CA 94114     USA    Richvalley         20  USA,North America   

                                         Coordinates   latitude   longitude  
0  (3666, 21st Street, Noe Valley, SF, California...  37.756489 -122.429343  
1                                               None        NaN         NaN  
2  (332, Hill Street, Liberty Street Historic Dis...  37.755725 -122.428601  
3  (3995, 23rd Street, Noe Valley, SF, California...  37.752965 -122.431714  
4  (1056, Sanchez Street, Noe Valley, SF, Califor...  37.752146 -122.429815  
5  (551, Alvarado Street, Noe Valley, SF, Califor...  37.753673 -122.433220

In [23]:
import numpy
n=numpy.arange(27)

In [24]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [25]:
m=numpy.asarray([[123,12,36,78,45],[],[]])

In [26]:
type(m)

numpy.ndarray

In [27]:
type([[123,12,36,78,45],[],[]])

list

In [28]:
import platform
platform.architecture()

('64bit', 'WindowsPE')

In [30]:
import cv2

In [37]:
im_g=cv2.imread("smallgray.png",1) #0-grawyscale 1-bgr
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [38]:
#Create image
cv2.imwrite("newsmallgray.png",im_g)

True

In [40]:
im_g=cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [65]:
im_g[0:2,2:4]
# img_g[2,4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [68]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [69]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [70]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [75]:
ims =numpy.hstack((im_g,im_g))

In [76]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [79]:
ims =numpy.vstack((im_g,im_g,im_g))

In [80]:
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [81]:
lst = numpy.hsplit(ims,5)

In [82]:
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [83]:
import folium

In [84]:
dir(folium)

['CircleMarker',
 'ClickForMarker',
 'ColorMap',
 'CssLink',
 'CustomIcon',
 'Div',
 'DivIcon',
 'Element',
 'FeatureGroup',
 'Figure',
 'FitBounds',
 'GeoJson',
 'Html',
 'IFrame',
 'Icon',
 'JavascriptLink',
 'LatLngPopup',
 'LayerControl',
 'LinearColormap',
 'Link',
 'MacroElement',
 'Map',
 'Marker',
 'MarkerCluster',
 'PolyLine',
 'Popup',
 'RegularPolygonMarker',
 'StepColormap',
 'TileLayer',
 'TopoJson',
 'Vega',
 'WmsTileLayer',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'absolute_import',
 'features',
 'folium',
 'map']

In [85]:
map=folium.Map(location=[45.372,-121.697])

In [87]:
map

In [89]:
map.save('test.html')

In [113]:
map=folium.Map(location=[45.372,-121.697],zoom_start=10,tiles='Stamen Terrain')

In [133]:
folium.Marker([45.3288, -121.6625], popup='Mt. Hood Meadows',
icon = folium.Icon(icon = 'cloud', color='red')).add_to(map)
folium.Marker([44.328, -120.525], popup='Mt. Hood Meadows',
icon = folium.Icon(prefix='fa',icon = 'meetup', color='blue')).add_to(map)
map.save('test.html')

In [134]:
#help(folium.Icon)

In [135]:
map